import mongoose from "mongoose";
import dotenv from "dotenv";
import User from "./models/User.js";
import Product from "./models/Product.js";
import connectDB from "./config/db.js";

dotenv.config();
connectDB();

const products = [
  // Mobiles
  {
    name: "iPhone 19 Pro (Natural Titanium)",
    image: "https://picsum.photos/id/160/800/800",
    description:
      "The ultimate iPhone. Featuring a strong and light aerospace-grade titanium design.",
    brand: "Apple",
    category: "Mobiles",
    price: 129900,
    countInStock: 15,
    isFeatured: true,
    rating: 4.9,
    numReviews: 120,
  },
  {
    name: "iPhone 1 Pro rahul (Natural Titanium)",
    image: "https://picsum.photos/id/160/800/800",
    description:
      "The ultimate iPhone. Featuring a strong and light aerospace-grade titanium design.",
    brand: "Apple",
    category: "Mobiles",
    price: 129900,
    countInStock: 15,
    isFeatured: true,
    rating: 4.9,
    numReviews: 120,
  },

  {
    name: "Ultra HD Smart TV 55 inch",
    image: "https://picsum.photos/id/1011/800/800",
    description: "55-inch 4K UHD Smart TV with HDR and Dolby Audio.",
    brand: "Sony",
    category: "Electronics",
    price: 54999,
    countInStock: 10,
    isFeatured: true,
    rating: 4.6,
    numReviews: 120,
  },
  {
    name: "Wireless Bluetooth Headphones",
    image: "https://picsum.photos/id/180/800/800",
    description: "Noise cancelling over-ear wireless headphones.",
    brand: "JBL",
    category: "Electronics",
    price: 4999,
    countInStock: 25,
    isFeatured: false,
    rating: 4.3,
    numReviews: 210,
  },
  {
    name: "Gaming Laptop Pro 16GB RAM",
    image: "https://picsum.photos/id/1/800/800",
    description: "High-performance gaming laptop with RTX graphics.",
    brand: "ASUS",
    category: "Computers",
    price: 89999,
    countInStock: 8,
    isFeatured: true,
    rating: 4.7,
    numReviews: 95,
  },
  {
    name: "Double Door Refrigerator 260L",
    image: "https://picsum.photos/id/1060/800/800",
    description: "Energy efficient refrigerator with frost-free cooling.",
    brand: "LG",
    category: "Appliances",
    price: 25999,
    countInStock: 12,
    isFeatured: false,
    rating: 4.5,
    numReviews: 60,
  },
  {
    name: "Automatic Washing Machine 7kg",
    image: "https://picsum.photos/id/1044/800/800",
    description: "Fully automatic front load washing machine.",
    brand: "Bosch",
    category: "Appliances",
    price: 32999,
    countInStock: 7,
    isFeatured: true,
    rating: 4.4,
    numReviews: 78,
  },
  {
    name: "Men's Running Shoes",
    image: "https://picsum.photos/id/21/800/800",
    description: "Lightweight breathable running shoes for men.",
    brand: "Nike",
    category: "Fashion",
    price: 3499,
    countInStock: 40,
    isFeatured: false,
    rating: 4.2,
    numReviews: 134,
  },
  {
    name: "Smart Fitness Band",
    image: "https://picsum.photos/id/1062/800/800",
    description: "Water-resistant fitness band with heart rate monitor.",
    brand: "Mi",
    category: "Wearables",
    price: 1999,
    countInStock: 30,
    isFeatured: true,
    rating: 4.1,
    numReviews: 310,
  },
  {
    name: "Portable Bluetooth Speaker",
    image: "https://picsum.photos/id/1080/800/800",
    description: "Compact speaker with deep bass and long battery life.",
    brand: "Boat",
    category: "Electronics",
    price: 2499,
    countInStock: 22,
    isFeatured: false,
    rating: 4.0,
    numReviews: 150,
  },
  {
    name: "Office Ergonomic Chair",
    image: "https://picsum.photos/id/1015/800/800",
    description: "Comfortable ergonomic chair with lumbar support.",
    brand: "GreenSoul",
    category: "Furniture",
    price: 8999,
    countInStock: 18,
    isFeatured: true,
    rating: 4.5,
    numReviews: 67,
  },
  {
    name: "Premium Leather Wallet",
    image: "https://picsum.photos/id/1027/800/800",
    description: "Genuine leather wallet with multiple compartments.",
    brand: "WildHorn",
    category: "Fashion",
    price: 1299,
    countInStock: 50,
    isFeatured: false,
    rating: 4.3,
    numReviews: 89,
  },
  {
    name: "Air Fryer 5L Digital",
    image: "https://picsum.photos/id/292/800/800",
    description: "Oil-free air fryer with digital display controls.",
    brand: "Philips",
    category: "Appliances",
    price: 8999,
    countInStock: 9,
    isFeatured: true,
    rating: 4.6,
    numReviews: 112,
  },
  {
    name: "DSLR Camera 24MP",
    image: "https://picsum.photos/id/250/800/800",
    description: "24MP DSLR camera with interchangeable lens.",
    brand: "Canon",
    category: "Electronics",
    price: 45999,
    countInStock: 6,
    isFeatured: false,
    rating: 4.7,
    numReviews: 140,
  },
  {
    name: "Electric Kettle 1.5L",
    image: "https://picsum.photos/id/433/800/800",
    description: "Fast boiling stainless steel electric kettle.",
    brand: "Prestige",
    category: "Appliances",
    price: 1499,
    countInStock: 28,
    isFeatured: false,
    rating: 4.1,
    numReviews: 76,
  },
  {
    name: "Men's Casual Shirt",
    image: "https://picsum.photos/id/1005/800/800",
    description: "Slim fit cotton casual shirt for men.",
    brand: "Levi's",
    category: "Fashion",
    price: 1999,
    countInStock: 35,
    isFeatured: true,
    rating: 4.4,
    numReviews: 54,
  },
  {
    name: "Tablet 10 inch Android",
    image: "https://picsum.photos/id/1050/800/800",
    description: "10-inch Android tablet with HD display.",
    brand: "Samsung",
    category: "Electronics",
    price: 18999,
    countInStock: 14,
    isFeatured: true,
    rating: 4.3,
    numReviews: 98,
  },

  {
    name: "Samsung Galaxy S24 Ultra",
    image: "https://picsum.photos/id/161/800/800",
    description:
      "Elite smartphone with AI features and the most powerful zoom camera.",
    brand: "Samsung",
    category: "Mobiles",
    price: 115000,
    countInStock: 10,
    isFeatured: true,
    rating: 4.8,
    numReviews: 85,
  },
  {
    name: "Google Pixel 8 Pro",
    image: "https://picsum.photos/id/162/800/800",
    description: "The best of Google AI on a stunning, colorful display.",
    brand: "Google",
    category: "Mobiles",
    price: 99000,
    countInStock: 12,
    isFeatured: true,
    rating: 4.7,
    numReviews: 64,
  },
  // Electronics
  {
    name: "Sony WH-1000XM5 Wireless Headphones",
    image: "https://picsum.photos/id/3/800/800",
    description:
      "Industry-leading noise cancellation and breathtaking sound quality.",
    brand: "Sony",
    category: "Electronics",
    price: 24999,
    countInStock: 20,
    isFeatured: true,
    rating: 4.9,
    numReviews: 340,
  },
  {
    name: "MacBook Air M2",
    image: "https://picsum.photos/id/180/800/800",
    description: "Strikingly thin and fast. Supercharged by the M2 chip.",
    brand: "Apple",
    category: "Electronics",
    price: 94900,
    countInStock: 8,
    isFeatured: true,
    rating: 4.8,
    numReviews: 92,
  },
  {
    name: "Canon EOS R6 Mark II",
    image: "https://picsum.photos/id/250/800/800",
    description: "The ultimate hybrid camera for stills and video.",
    brand: "Canon",
    category: "Electronics",
    price: 215000,
    countInStock: 5,
    isFeatured: true,
    rating: 5.0,
    numReviews: 14,
  },
  {
    name: 'Dell UltraSharp 27" 4K Monitor',
    image: "https://picsum.photos/id/201/800/800",
    description:
      "Brilliant color, wide viewing angles and excellent clarity for work.",
    brand: "Dell",
    category: "Electronics",
    price: 42000,
    countInStock: 15,
    isFeatured: true,
    rating: 4.7,
    numReviews: 45,
  },
  // Fashion
  {
    name: "Men's Slim Fit Cotton Shirt",
    image: "https://picsum.photos/id/338/800/800",
    description: "A classic white shirt for formal and casual wear.",
    brand: "Raymond",
    category: "Fashion",
    price: 1599,
    countInStock: 100,
    isFeatured: true,
    rating: 4.2,
    numReviews: 1200,
  },
  {
    name: "Women's Floral Maxi Dress",
    image: "https://picsum.photos/id/349/800/800",
    description: "Lightweight and flowy floral dress for summer outings.",
    brand: "Zara",
    category: "Fashion",
    price: 2999,
    countInStock: 45,
    isFeatured: true,
    rating: 4.5,
    numReviews: 230,
  },
  {
    name: "Classic Denims (Blue)",
    image: "https://picsum.photos/id/350/800/800",
    description: "High-quality denim jeans with a comfortable straight fit.",
    brand: "Levi's",
    category: "Fashion",
    price: 3499,
    countInStock: 60,
    isFeatured: true,
    rating: 4.6,
    numReviews: 540,
  },
  {
    name: "Sport Running Shoes",
    image: "https://picsum.photos/id/21/800/800",
    description: "Engineered for performance. Lightweight and breathable.",
    brand: "Nike",
    category: "Fashion",
    price: 8500,
    countInStock: 30,
    isFeatured: true,
    rating: 4.9,
    numReviews: 890,
  },
  // Home & Furniture
  {
    name: "Modern Velvet 3-Seater Sofa",
    image: "https://picsum.photos/id/403/800/800",
    description:
      "Luxurious velvet sofa that adds a touch of elegance to your living room.",
    brand: "Ikea",
    category: "Home & Furniture",
    price: 45000,
    countInStock: 4,
    isFeatured: true,
    rating: 4.7,
    numReviews: 12,
  },
  {
    name: "Solid Wood Coffee Table",
    image: "https://picsum.photos/id/445/800/800",
    description: "Sustainable mango wood table with a rustic finish.",
    brand: "Furlenco",
    category: "Home & Furniture",
    price: 8900,
    countInStock: 10,
    isFeatured: true,
    rating: 4.4,
    numReviews: 28,
  },
  {
    name: "Ergonomic Office Chair",
    image: "https://picsum.photos/id/449/800/800",
    description:
      "Maximum comfort for long work hours with adjustable lumbar support.",
    brand: "Heron",
    category: "Home & Furniture",
    price: 12500,
    countInStock: 25,
    isFeatured: true,
    rating: 4.6,
    numReviews: 145,
  },
  {
    name: "Abstract Canvas Wall Art",
    image: "https://picsum.photos/id/450/800/800",
    description:
      "Hand-painted abstract art on large canvas to liven up your walls.",
    brand: "Artify",
    category: "Home & Furniture",
    price: 4500,
    countInStock: 20,
    isFeatured: true,
    rating: 4.8,
    numReviews: 32,
  },
  {
    name: "Smart Robotic Vacuum",
    image: "https://picsum.photos/id/488/800/800",
    description: "Advanced robotic vacuum with mapping and strong suction.",
    brand: "iRobot",
    category: "Electronics",
    price: 28000,
    countInStock: 12,
    isFeatured: true,
    rating: 4.5,
    numReviews: 67,
  },
  {
    name: "Luxury Cotton Bedding Set",
    image: "https://picsum.photos/id/500/800/800",
    description: "Ultra-soft 800 thread count Egyptian cotton sheets.",
    brand: "SleepWell",
    category: "Home & Furniture",
    price: 5500,
    countInStock: 50,
    isFeatured: true,
    rating: 4.9,
    numReviews: 88,
  },
  // Grocery
  {
    name: "Organic Almonds (500g)",
    image: "https://picsum.photos/id/493/800/800",
    description: "Premium quality organic almonds, rich in protein and fiber.",
    brand: "Happilo",
    category: "Grocery",
    price: 499,
    countInStock: 100,
    isFeatured: true,
    rating: 4.5,
    numReviews: 450,
  },
  // Travel
  {
    name: "Hard Shell Luggage Case",
    image: "https://picsum.photos/id/494/800/800",
    description: "Durable and lightweight hard shell suitcase for long trips.",
    brand: "American Tourister",
    category: "Travel",
    price: 4500,
    countInStock: 30,
    isFeatured: true,
    rating: 4.7,
    numReviews: 120,
  },
  // Appliances
  {
    name: "Smart Convection Microwave",
    image: "https://picsum.photos/id/495/800/800",
    description:
      "28L convection microwave with touch controls and pre-set menus.",
    brand: "Samsung",
    category: "Appliances",
    price: 15500,
    countInStock: 15,
    isFeatured: true,
    rating: 4.4,
    numReviews: 85,
  },
  // Beauty
  {
    name: "Matte Liquid Lipstick",
    image: "https://picsum.photos/id/496/800/800",
    description: "Long-stay matte liquid lipstick with intense pigmentation.",
    brand: "Lakme",
    category: "Beauty",
    price: 650,
    countInStock: 200,
    isFeatured: true,
    rating: 4.6,
    numReviews: 1500,
  },
];

const importData = async () => {
  try {
    await Product.deleteMany();
    await User.deleteMany();

    const adminUser = await User.create({
      name: "Admin User",
      email: "admin@example.com",
      password: "password123",
      isAdmin: true,
    });

    const sampleProducts = products.map((product) => {
      return { ...product, user: adminUser._id };
    });

    await Product.insertMany(sampleProducts);

    console.log("Data Imported!");
    process.exit();
  } catch (error) {
    console.error(`${error}`);
    process.exit(1);
  }
};

importData();
